notifications: 
  hipchat: 
    template: 
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    rooms: 
    - b7098c17bc3283dc7ca388b68e3ca3@m3
    format: html
install: true
python: 
- "2.7"
deploy: 
  distributions: sdist
  on: 
    tags: true
    all_branches: true
  password: 
    secure: EkfjfFra6/i3otmXthO1kyrNh2n8ahm14QyKCx4AfX8ES2/vncWl8VcBToerwGu6AyrUyxOe1OCfaAIk/0emJgfqHF0X29X3yI1R/qZlV7/ZmnuH0oCJSuOvbgI70B0U8nkAgQj7ctnRPBAGVpEYKFAh556fcpkRgBqXO9ZxGZoc/YjFvxEIkJIwcj7iXyJW3/QLzMb6JwNYA0RmBQieJRQ/9ctKcQVZXK1k25R+vBibSzPOQRV7SfE8cgWQ8RtEffmJgQpTZlzh29iXAvbSPUXMMhduBAP6py1cERJqkGaX8iaRd7kwk8lTIZhyjdVioxhCCUvXH+redrqA0vxlMX2IDeHEieJPaJAeeBhNSEgH+BkXExa7SmNhVoWkkJDC3wnx2KqfJIF6LXWRj+U1L+zAHkRWaepfv/h6IzW6hatw3PMxGEfStE2lNKrdKl8VsvoaIyiNK5UBMKWvnBl7qH7Bte0anI3KSeZo9AVmrkIm/T9ayQjFIOy5TzaXoh+92IXePlFTuuGltxWm88ctpBt9xCLOKPuPoNtQjKOJeb3ysx/BlWM0oJplt5TOXI1zyCgFqqTW0cDSYpkI6xk/i3nKZIPkl8dTn0W2ge5HJDY2XhMu2ZmAz5dyP4cpYqyICUfs1Jx4QY9eTqOJFHfkPbP5vPBoOqOkv1sKbENbkxY=
  user: bars-travis
  provider: pypi
script: true
language: python
