script: true
install: true
language: python
python:
- '3.6'
deploy:
  provider: pypi
  user: bars-travis
  password:
    secure: YclWf5L07fPtnHK1vlHEoDkWXWTgaHIPXndAnz6Spn+DWj1pX0P8R9uv7Ks2HVv8R7FPVO6t+b8hGUfAbXpRWbe8/yuBp15lKwzH2khJjAsF0DkbUhHSr1YK1Fv6zqHo6M4gXUKCDg+Hy/sl6mtTuOM5ip50AEy3tHdoISrAN/xh0NokYKYAmsFHuO1NeCZFcj9cXObHR4ESGJG55uvq65Xj5G088VZk1WZbwuefC54zAQg4R5ptgh/R/gvupU+9mORiZq2s+6LqViwiOtFg9oBkA18G/YV+JPEF4yEazkmXowQ/18PI7Y9npwidTttC59y6ecEWUe6ozy3wRSL4NlCuKYc99vxnot8XjREtqqcKWF3cwZBOR35QZrGfk+C/zBzBlJ7fcpThiY2PwY+hZBLMX0gajoIxKK7GRLcB5PPNj6jeWewPP4YFV3kxXhrXu2j9GHSzL7lRF/H5mu8lq5EDcKW2+YnNsiCay+kFXkabBeWReNHSmITdkOZquRBmCFqOW/5B4sN4bRYGMKNE1RJKnC5xFTfBLG5eVZ+Uyy7tbCH/plw87fl7tOSuRTrE4FmXk76e8dbpT+uUMTpwgYj5VJ5xKAcMZYLUZAusfhDwOHQHVN2fvuXrmiX8hDgAwUKf3alukfqFQxuN0NUdFu6+aaziEQTZHYk+OBdgT9A=
  on:
    tags: true
  distributions: sdist
notifications:
  email:
    recipients:
    - dev-py@bars-open.ru
